import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Button from 'react-bootstrap/Button';
import { useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const nameRef = useRef<HTMLInputElement>(null);
  const emailRef = useRef<HTMLInputElement>(null);
  const messageRef = useRef<HTMLTextAreaElement>(null);  

  const handleSubmit = async (e : React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    let data = {
      name: nameRef.current?.value,
      email: emailRef.current?.value,
      message: messageRef.current?.value,
    }

    await fetch("api/contact", {
      method: "POST",
      headers: {
        Accept: "application/json, text/plain",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    }).then((res) => {
      if (res.status === 200) {
        console.log('Success');
      }
    });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="container mt-5">
        <h2 className="mb-3">Next.js Gmail App</h2>
        <form onSubmit={(e: React.FormEvent<HTMLFormElement>) => handleSubmit(e)}>
          <div className="mb-3">
            <label htmlFor="name" className="form-lable">
              Name
            </label>
            <input type="text" className="form-control" id="name" required ref={nameRef}/>
          </div>
          <div className="mb-3">
            <label htmlFor="mail" className="form-lable">
              Mail Address
            </label>
            <input type="email" className="form-control" id="mail" required ref={emailRef}/>
          </div>
          <div className="mb-3">
            <label htmlFor="message" className="form-lable">
              Message
            </label>
            <textarea name="message" className="form-control" id="message" required ref={messageRef}/>
          </div>
          <button type="submit" className="btn btn-danger">
            Send
          </button>
        </form>
      </div>
    </>
  );
}
